travis:
  secure:
    BINSTAR_TOKEN: JXHzhTFQupZM5pZxfgcy3PCbDXnL/Cr+9pfdrQII8DxQZr1c4kYERgvl7WpfBChrEnV4lZz6eERWi3RSFkTvPSm97/vv3vYOfTDsr3G4oSxVIa8DGRlsL6TDMXIB6djnJ5YQygFUOqAc+G8y4y+gyvSN4YrOVaxDzVnhln+HPetyXla+P3k2kX4UcvPS/YdZGwRt6iVUUrzCWHALgRSou4qQupGgAqRTCRW2KU6DKts+/KNLEYb9IbljmfHYZUzkEcr6QJ++/IbjoNM2CorTVty/B1qMNug97Su7zmOBFhF2blLtTBK0a4ePpjgL5t9JisjFtjpDBQH4sWce24w0q0WRsvj6dJO5e82ycUHvHOkDf99gez7WvNS8WOFbTXc0d6DO1hIOWUxIaSk6CPwNY5jdF/pFuhfzKs7C1AFE3OdBF2fl+2IxMUIX3inKJp/ebBwSmqyBJn+JawopJioiiuNcdJ1gv7Ke5TNqisbyPYsALKRQV4tqnvHMh+woUeRxdWevJOnNhlIXWxuifDEJpM0CirDWa0n2z4f4ZqlQl3qvz2RUimElCvJUv4FFKQM7kPi9F3N4Y9cUNSyd8FpVooRtpW4NBu0erCRvobbVvscwYm5VehvDbzbkmWpXDMte+aQKyhnDlsW7psdx0jMcM7H8w0dYxyU3NnIvvrr8ahk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
