travis:
  secure:
    BINSTAR_TOKEN: NgS4FPBE9aDUf7grbauQKE586SodroIDv1OBIdBkKJv6qV0eVYVwGoBjEZSQnjvDyI1Zn8N4d/WNg/jnDOms08VMS5NGG0j9ak7UVAEUdEDXm43P6dZYz7iyvRiowLzrDzbf0YaJe88h9J13lccVMwo15hsQaZtBRWVkwbtLzxMLNsYlYe19wUTNj9UytgAGOUcJT5ZD2eat2zyF7/6OCq2r+kg12ojHAtZU+izDHPzpMjFJfS7yVNG2FZ/jDCQgypftnrTNVh7kdQHWuxBo7fA0G2yeDV+6pMgLxWEJn2MmIrFRKVpCT1am+XdoZ6Vu8VEJdF1lLnXdgyuC0xLAOZLhiuhWczKJ7IQvbdRAqRsi/obHNevrSRn63YLbg2pmvkID6l8xxddZSL2LzGJ89CDnH7x0ZO5cnf6KnsEmnjhxLGdy/dfNBzqUnGazC9JZwSaik3JjRnHYELJZ0CdKKhv2c9tbtVlF9mJGGVnn+mPoXwDfWHahjh/6gXnHlZ82QoAAa7i3FF4xKUjfB9RNRBMEDpctwggHyEKLhLQkdV1EuGq/UziqWRASWlpPgjQ1e4Hn8clG0ywuRHQc5dg/ZXPaGYp4ufwG1iZUvtbbVvjWVB+WiSzZAqZbzCyy4w1pG3n9kj33WjN1PEE5CXSYKi8NCI0YSxkvv/E+dU973Ag=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
